### ISSUE TITLE
(node:38752) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by samreid** [phetsims/binder#12]
To see what other sims use ProbeNode for https://github.com/phetsims/wave-interference/issues/24, I instrumented ProbeNode and ran:

> cd js/; node generate.js;

and received this error:
```
loading: wave-on-a-string
wave-on-a-string PAGE LOG: enabling assert
wave-on-a-string PAGE LOG: loaded wave-on-a-string
(node:38752) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at sims.forEach.sim (/Users/samreid/github/binder/js/createHTMLString.js:25:41)
    at Array.forEach (<anonymous>)
    at createHTMLString (/Users/samreid/github/binder/js/createHTMLString.js:24:8)
    at __dirname (/Users/samreid/github/binder/js/generate.js:43:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:38752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by samreid** [comment]
When I subsequently ran

> node createHTMLString.js json binderjson.json > html.html

It worked OK

**Comment by mbarlow12** [comment]
We're returning a Promise that resolves to `undefined` when there's no InstanceRegistry in the sim. I refactored the code a bit so that the data is organized by component, and sims that don't have components don't appear.

It's still a bit messy, but it's working without error at this point. Also, I changed the localhost port to 8080.

**Comment by zepumph** [comment]
>Also, I changed the localhost port to 8080.

@samreid and I both use localhost off of port 80, is there a way that we can specify an option to the process that will indicate the port number? This is probably a different issue. For example, I know that @pixelzoom uses a completely different path for his server. This sounds like a nice thing to potentially add to a config file, maybe `build-local.json`?

**Comment by mbarlow12** [comment]
@zepumph great suggestion—I'll make an issue.

**Comment by mbarlow12** [comment]
Standard generation is no longer throwing exceptions. Closing.
