### ISSUE TITLE
Add build-local.json check for local development

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/binder#13]
We've hardcoded the address of a local development. @zepumph noted in https://github.com/phetsims/binder/issues/12 that this should be configurable for different environments. To allow for this, we'll add a check in `~/.phet/build-local.json` for the following keys:
```json
{
    "localHostURL": "http://localhost",
    "localHostPort": "8080"
}
```

Since node's `http-server` runs the server configured above, those will be the defaults.

- [x] Add `build-local.json` check and defaults for setting the local dev server URL in `getFromSimInMaster.js`.
- [x] Add config options to README

**Comment by zepumph** [comment]
I would also recommending loud asserts if those keys are not present when running.

**Comment by mbarlow12** [comment]
All that's left for this is to update the documentation. To generate the docs, `binder` looks in `build-local.json` for the following:
```json
{
  "localhostURL": "https://someUrl",    // REQUIRED with asserts
  "localhostPort": "42"   // optional
}
```
It uses https://github.com/phetsims/perennial/blob/master/js/common/buildLocal.js to access the local configuration, so the getters have been added.

**Comment by jonathanolson** [comment]
I'm not sure why the URL and port are separated, since the port could be part of the URL. How do you plan to handle `http://localhost:8080/something/`? It seems like it would be easier (and fixes this issue) to have it be part of one URL.

**Comment by mbarlow12** [comment]
@jonathanolson That's true—I think that'd be a worthwhile change. It's just been a habit for a long time to separate the port.

**Comment by pixelzoom** [comment]
FYI, I'm using port 80 because it's the default for Apache on macOS.  It can be configured in /etc/apache2/httpd.conf.

**Comment by mbarlow12** [comment]
@pixelzoom do you see problems arising from using a single key in build-local.json for both the host and port?

**Comment by pixelzoom** [comment]
I've been out of the loop wrt binder, so much so that I have no idea why a host and port are even needed.   Try it and see?

**Comment by mbarlow12** [comment]
README updated. Closing.
