### ISSUE TITLE
Host docs from gh-pages branch

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/binder#17]
Trouble found from the changes in https://github.com/phetsims/tasks/issues/936. GitHub mandates that pages use a`docs/` directory. So for binder, we'll follow the method of scenery and use a new gh-pages branch to properly host the generated HTML.

**Comment by zepumph** [comment]
Why couldn't we just use all of master? Then the style guide can be found on at `binder/doc/`

![image](https://user-images.githubusercontent.com/6856943/40796165-a45f9a4e-64b0-11e8-8f0a-e5712abe297e.png)

**Comment by zepumph** [comment]
I worry about putting it on a branch, because that would be one more step to keep it up to date with master. I defer to your judgement.

**Comment by mbarlow12** [comment]
The issue there is that the root directory is the root of the repo, so it defaults to displaying the README located there. It may be possible to replace that file with the generated index.html and link to any necessary resources from the root.

One other option would be to create a `documentation` or`docs` repo that would act as the public face of all PhET documentation. Binder would then be responsible for gathering and processing various data from the other repos and compiling assets into a single destination. Custom pages that aren't necessarily associated with a specific repo could also be added there.

**Comment by zepumph** [comment]
Or we could just keep the name `docs/` seeing as it is obviously nicer to have it that way, and we can document why this is different from every other docish folder in the project.

**Comment by mbarlow12** [comment]
True—I also realize that there's a grunt task for updating the gh pages branches in all sims. Perhaps @jonathanolson would have an opinion on integrating binder with that task and building all documentation into a single place?

**Comment by mbarlow12** [comment]
@zepumph I also agree that in binder, the doc/ directory isn't actually documenting anything in the repo whereas sun's doc/ folder actually contains details on sun components implementation.

**Comment by zepumph** [comment]
@ariel-phet gave me the go ahead to rename all to `doc/`, so I would ask him if you want to keep binder `docs/` to make hosted github pages easier for the style guide.

**Comment by jonathanolson** [comment]
> Perhaps @jonathanolson would have an opinion on integrating binder with that task and building all documentation into a single place?

That would definitely be doable. I haven't run that task recently, and I'd need to check it a bit before having it "ready" to be used for other things.

**Comment by mbarlow12** [comment]
I actually think this will be really easy, especially if we integrate it with some kind of a build step. Essentially, we checkout only the gh-pages branch from within the `doc/` directory and delete the refs to all other branches.

Then we compile/create the assets and push. In this way, we can also name the directory whatever we want. `doc/` can be retained for housing the documentation `.md` files, and another directory (e.g. `pages/` or `site/`) can be used to house the `gh-pages` branch.
