### ISSUE TITLE
branch: yamldocs

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/binder#20]
Proposed in https://github.com/phetsims/binder/issues/15, the binder branch will handle parsing of YAML front matter within the build process. We'll make use of https://github.com/jonschlinkert/gray-matter.

**Comment by mbarlow12** [comment]
Branch merged into master. See 596ba4f32a0ccef684c04e926f088407cfefbcb9.

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198

**Comment by chrisklus** [comment]
branch re-deleted, closing
