### ISSUE TITLE
HSlider documentation should be renamed to Slider

### ISSUE THREAD

**Issue by zepumph** [phetsims/binder#22]
From https://github.com/phetsims/sun/issues/380, now the logic is in the `Slider` file, with `HSlider` and `VSlider` as convenience types. The documentation should reflect that and just say "Slider"

**Comment by zepumph** [comment]
@mbarlow12 can you make sure that the above commit is all that needs to be done? Does anything need to be rebuilt? I'm really out of touch with this repo these days, can you take over or assign to the best person for the job?

**Comment by mbarlow12** [comment]
@zepumph yes, that's the only place where info specific to our components needs to be changed. `binder` just stitches that with the `InstanceRegistry` data. Feel free to close.
