### ISSUE TITLE
Redundant/broken list of sims under "Simulations and their components"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/binder#24]
Related to https://github.com/phetsims/tasks/issues/980#issuecomment-507938420

Under http://phettest.colorado.edu/binder/doc/#sims, there are two lists of simulations. The list at the bottom which binder autoscrolls to when clicking "Simulations and their components' in the sidebar is not functional.

**Comment by zepumph** [comment]
The above fixes this bug. There is now only one list. I also renamed the nav section to be "Components by sim". Closing

**Comment by zepumph** [comment]
See http://phettest.colorado.edu/binder/doc
