### ISSUE TITLE
Add inverse component/sim lookup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/binder#25]
In https://github.com/phetsims/tasks/issues/980#issuecomment-507938420 @zepumph added a list of sims with an expandable menu listing the common code components used within it.

![image](https://user-images.githubusercontent.com/8419308/60611441-88a06380-9d83-11e9-8c63-19d19fd9428e.png)

It would be extremely helpful to also have the inverse of this list. That is, add a list of common components with expandable menu listing the sims which contain that component. This is a stop-gap measure until a complete, functional style guide is a reality.

The long-term vision for binder is for each common component to have its own page (eg. [ComboBox](https://phetsims.github.io/binder/#sun-ComboBox)) which contains visual examples of the component in each sim. 

![image](https://user-images.githubusercontent.com/8419308/60611698-272cc480-9d84-11e9-9ee9-0d4ded5d27d6.png)

**Comment by zepumph** [comment]
This is now implemented, though still not pretty. @arouinfar please review. 

http://phettest.colorado.edu/binder/doc/

**Comment by arouinfar** [comment]
Thanks @zepumph! The reverse look up seems to be working well! After some cursory testing, it looks like the components-by-sim and sims-by-components are being properly populated.

One thing I realize in seeing the sims-by-component is that we're missing a LOT of common code components from this list, so I'll open a separate issue for a UI component wishlist.
