### ISSUE TITLE
CT: Parsing error: Unexpected token <

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/binder#33]
Reported in Slack#continuous-testing:

@KatieWoe:
Binder is failing with:

```
binder : lint
Lint failed with status code 1:
Running "lint" task

/data/share/phet/continuous-testing/ct-main/ct-snapshots/1696929371211/binder/docs/index.html
1:1 error Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)

Fatal error: Lint failed
Snapshot from 10/10/2023, 3:16:11 AM
```

@pixelzoom:
Reproduced in my working copy by running `cd binder; grunt lint`. Looks like it started failing CT 10/7/2023 @ 10:04AM. That is minutes after @zepumph  announced a lint improvement in https://phetsims.slack.com/archives/G6E0RA1T2/p1696693897098669, so I suspect they are related. I’ll create an issue in binder.
> @channel I'm very excited to report that eslint now works in script tags of our HTML files. Upon next pull please npm update in chipper/ and report any trouble to https://github.com/phetsims/chipper/issues/1405. Thanks!

@zepumph:
Excellent. I'll take a look

**Comment by zepumph** [comment]
This should take care of it. While I was add it, I found that the eslintignore was pretty useless, so I added it to the central eslintignore.  I'll check back later.

**Comment by zepumph** [comment]
Fixed in this row. Closing
