### ISSUE TITLE
Delete binder/js/binderjson.json?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/binder#35]
There are 2 binderjson.json files.

binder/binderjson.json is updated by daily grunt work. It was create by @zepumph on 5/28/18.

binder/js/binderjson.json was also created by @zepumph on 5/28/18, and has never been updated.  Should it be deleted?

**Comment by zepumph** [comment]
Looks like you're right. We should delete this. 

> binder/js/binderjson.json was also created by @zepumph on 5/28/18, and has never been updated. Should it be deleted?

It was created by Michael Barlow, probably when iterating and creating the repo initially.
