### ISSUE TITLE
Where should the component documentation be?

### ISSUE THREAD

**Issue by samreid** [phetsims/binder#4]
As part of the component documentation, we plan to write MD (markdown) files that describe the corresponding JS (javascript) files. Binder will combine the MD files with automatically generated information to create the overall documentation.  

When I recommended to put the MD files next to the JS files, I was told that there was a prior consensus to put the documentation files "elsewhere".  I don't know what the arguments were for putting them elsewhere, but I recommend to keep them in the same directory as the component they document, for the following reasons:

PRO-1. This will encourage developers to be more aware of the MD files, and hence to see them, read them, and keep them up-to-date.  For example, if a developer is changing a feature in ComboBox.js, they will have a better chance to update ComboBox.md if it is nearby.
PRO-2. Subtly different than the first point: The ComboBox.md and the ComboBox.js should generally evolve together.  It seems odd that if we are updating ComboBox.js and ComboBox.md that we would push commits to two separate repos.  This is more of an argument for the same repo than the same directory.
PRO-3. It has worked well to keep other related files adjacent to the primary file.  For instance, ComboBox.js would be next to ComboBoxIO.js and ComboBoxTests.js and now also ComboBox.md.  Also, then you can look at a component JS file and easily see if it has all of its other related files, without having to hunt elsewhere.

I do not know what arguments were given for keeping the MD files separate from the JS files, but here are some reasons I can think of:

CON-1. This will clutter up the already crowded source code directories.  In my opinion, the advantage of PRO-3 seems to outweigh this.
CON-2. The source code directories are named "js" and hence should only contain JavaScript, not other file types. This seems like a reasonable argument, but not sure if it outweighs the PROS taken together.
CON-3. Keeping them in the same repository could create commit conflicts if developers are working on the design files at the same time as the developers are working on the same repo.  In my opinion, this problem is minimal, especially if designers are using the GitHub website to make changes.
CON-4. If the MD files require image files, we probably wouldn't want to keep those in the js/ folder and it could be odd to separate them from the MD files.

If we combine PRO-2 with CON-2, the conclusion would be to put the MD files in the same repo as the component, but in a different directory (perhaps docs/ or md/).  What was the recommended location for the MD files from the prior meeting?

**Comment by jonathanolson** [comment]
*.md in docs/ and images under the already-agreed docs/images (used for e.g. the area-model glossary) sounds nice, if that works?

**Comment by samreid** [comment]
That sounds great, thanks!  I'll close the issue for now, but if anyone objects to docs/ feel free to reopen.
